### ISSUE TITLE
Weekly Scrum - 2/3/17

### ISSUE THREAD

**Issue by rscarson** [rscarson/SYSC4806-AMA#17]

**Comment by adambatson** [comment]
What have I done this week
   Nothing this is the first week
What am I working on this week
   I'm working on the Posts Controller
What is holding me back
   Generally still learning a lot about how spring works

**Comment by MeloDeMelo** [comment]
What have I done this week
  I haven't done anything yet.
What am I working on this week
  I am working on #11  and #12 
What is holding me back
  what to put in them

**Comment by rscarson** [comment]
**This week** I have built basic templates for AMA related views needed for ms1
**Next week** I am make the frontend more user-friendly and helping with the views to link #12 and #14
