### ISSUE TITLE
Weekly scrum 12/3/17

### ISSUE THREAD

**Issue by adambatson** [rscarson/SYSC4806-AMA#33]
What have I done?

Last week I worked on the Posts Controller

What am I doing this week?

I need to beef up my unit tests for the post controller.  And start looking into building comments

Any impediments?

None right now.

**Comment by rscarson** [comment]
Last week I built the views for the post controller,

This week I will beef up the interface and investigate implementing OAuth

**Comment by MeloDeMelo** [comment]
What have I done?

Last week I worked on the UsersController

What am I doing this week?

Working on unit tests for user controller

Any impediments?

None right now.
