### ISSUE TITLE
Post is used by two names

### ISSUE THREAD

**Issue by rscarson** [rscarson/SYSC4806-AMA#51]
We call it post and ama... We should use one everywhere

**Comment by adambatson** [comment]
So the only real place I've found where this is an issue is the templates folder.  Which I think is fine since we're showing views of full AMA's and not just "Posts".  I can't find any actual references in the code where this is an issue?

**Comment by rscarson** [comment]
So is this a nofix? Because like you said it's not really an issue

**Comment by adambatson** [comment]
Yeah, I'd say no fix
